/**
 * Frontend entry-number check-digit — must match the server engine
 * (server/src/abi-engine/ae/checkDigit.ts, AE Table 1). Every vector
 * below was generated by running the engine's computeEntryCheckDigit.
 */
import { describe, it, expect } from 'vitest';
import { computeEntryCheckDigit, validateEntryNumberLocal } from './entryNumber';

describe('computeEntryCheckDigit (engine vectors)', () => {
  const VECTORS: Array<[string, string, number]> = [
    ['ABC', '1234567', 6],
    ['SP7', '0000001', 4],
    ['SP7', '1000000', 4],
    ['MCL', '9999999', 4],
    ['8CG', '0012345', 4],
    ['ZZ9', '7654321', 7],
  ];
  it.each(VECTORS)('%s-%s → %d', (filer, seq, expected) => {
    expect(computeEntryCheckDigit(filer, seq)).toBe(expected);
  });
});

describe('validateEntryNumberLocal', () => {
  it('accepts a correct number in hyphenated or flat form', () => {
    expect(validateEntryNumberLocal('SP7-0000001-4')).toEqual({
      valid: true,
      canonical: 'SP7-0000001-4',
    });
    expect(validateEntryNumberLocal('abc12345676')).toEqual({
      valid: true,
      canonical: 'ABC-1234567-6',
    });
  });

  it('flags a wrong check digit with the expected value', () => {
    const result = validateEntryNumberLocal('ABC-1234567-9');
    expect(result.valid).toBe(false);
    expect(result.expectedCheckDigit).toBe(6);
  });

  it('stays silent (valid) on partial input — the field is still being typed', () => {
    // Partial shapes are the schema's job; the check-digit hint only fires
    // on a fully-formed number so we never nag mid-keystroke.
    expect(validateEntryNumberLocal('SP7-00')).toEqual({ valid: true });
    expect(validateEntryNumberLocal('')).toEqual({ valid: true });
  });
});
